/* items info  */
const vkCB = {
    "A-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", ],
        "Red Crytal Big Smash v2": [
            "356", 
            "456", 
            "87.32", 
            "4", 
            "1300", 
            "0.9", 
            "56", 
            "1", 
            "1", 
            "100", 
        ],
        /* CB_MIN, CB_MAX, CB_CX, CB_XP, CB_Cự-ly, CB_ReA, CB_Quá-tải, CB_SHOTS, CB_MULTI, CB_Trọng-lượng */
        "Big Smash MK.III": ["167", "214", "85.00", "6", "1250", "0.43", "28", "1", "1", "90"], 
        "Big Smash MK.II": ["162", "209", "85.00", "5", "1250", "0.43", "28", "1", "1", "90"], 
        "Katharsis of Bishop": ["166", "214", "100.00", "0", "1300", "0.45", "56", "1", "1", "90"], 
        "Pyro Acid": ["134", "165", "100.00", "0", "1280", "0.4", "56", "1", "1", "100"], 
        "Atum Big Smash (+6) XP": ["166", "215", "90.00", "6", "1200", "0.45", "28", "1", "1", "100"], 
        "Atum Big Smash (+7) XP": ["166", "215", "90.00", "7", "1200", "0.45", "28", "1", "1", "100"], 
        "Valentine Jackhamme": ["80", "100", "100.00", "0", "1350", "0.22", "25", "1", "1", "130"], 
        "Zelus Navy Ver. Final": ["162", "209", "85.00", "0", "1200", "0.39", "30", "1", "1", "80"], 
        "Monthu": ["155", "200", "100.00", "0", "1300", "0.44", "32", "1", "1", "90"], 
        "Khonsu": ["122", "162", "85.00", "12", "1200", "0.43", "30", "1", "1", "150"], 
        "Omega Mount": ["235", "307", "80.00", "0", "1200", "21.98", "22", "2", "1", "120"], 
    },
    "B-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", ], 
        "Red Crytal Big Smash v2": [
            "356", 
            "456", 
            "87.32", 
            "4", 
            "1300", 
            "0.9", 
            "56", 
            "1", 
            "1", 
            "100", 
        ],       
    },
    "M-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", ],        
    },
    "I-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", ],        
    },
}
const vkCC = {
    "A-Gear": {
        "-": [
            "", "", "", "", "", "", "", "", "", "", "", "", "", 
        ],
        /* "CC_MIN", "CC_MAX", "CC_CX", "CC_XP", "CC_Tốc-độ", "CC_ReA", "CC_BKN", "CC_SHOTS", "CC_MULTI", "CC_Trọng-lượng", "CC_Góc-bắn", "CC_Góc-lượn", "CC_Cự-ly", */
        "Blue Crystal Terol v2": [
            "250",
            "360",
            "100.00",
            "5",
            "1000",
            "1.98",
            "100",
            "4",
            "1",
            "396",
            "11",
            "0",
            "4000",
        ],
        "Superior Inferno": [
            "200",
            "260",
            "100.00",
            "0",
            "1500",
            "1.98",
            "100",
            "4",
            "1",
            "380",
            "8",
            "0",
            "4500",
        ],
        "Guard MK.II": ["172", "240", "95.00", "5", "1000", "1.88", "100", "4", "1", "100", "11", "0", "4000"],  
    },
    "B-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", "", "", "", ],        
    },
    "M-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", "", "", "", ],      
    },
    "I-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", "", "", "", ],      
    },   
}
/*"NGC Guarder": {
            "HP": "7824",
            "DP": "9019",
            "Thủ_CB": "29.00",
            "Thủ_CC": "29.00",
            "Né_CB": "",
            "Né_CC": "",
            "CB_MIN": "25",
            "CB_MAX": "25",
            "CC_MIN": "",
            "CC_MAX": "",
            "CB_XP": "",
            "CC_XP": "",
            "CB_CX": "",
            "CC_CX": "",
            "Cự ly hữu hiệu VKCB": "",
            "Tốc độ VKCC": "",
            "Thời gian quá tải động cơ": "",
            "G_Trọng-lượng": "500",
        },*/
const tagGI = [
"HP","DP","Thủ_CB","Thủ_CC","Né_CB","Né_CC","CB_MIN","CB_MAX","CC_MIN","CC_MAX","CB_XP","CC_XP","CB_CX","CC_CX","CựlyhữuhiệuVKCB","TốcđộVKCC","Thờigianquátảiđộngcơ","G_Trọng-lượng",
]
const GIAP = {
    "A-Gear": {
        "-": [
          /*"HP","DP","Thủ_CB","Thủ_CC","Né_CB","Né_CC","CB_MIN","CB_MAX","CC_MIN","CC_MAX","CB_XP","CC_XP","CB_CX","CC_CX","CựlyhữuhiệuVKCB","TốcđộVKCC","Thờigianquátảiđộngcơ","G_Trọng-lượng"*/
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
        ],
        "U23-VN 2018 [AG] R": [
            "18488",
            "14941",
            "",
            "",
            "",
            "",
            "25",
            "25",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "300",
        ],
        "NGC Guarder": [
            "7824",
            "9019",
            "29.00",
            "29.00",
            "",
            "",
            "25",
            "25",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "500",
        ],
        "Halloween Guarder .5 (CX)": [
            "15480",
            "13132",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "14",
            "",
            "7",
            "",
            "",
            "780",
        ],
        "Halloween Guarder .5 (XP)": [
            "15480",
            "13132",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "12",
            "",
            "",
            "",
            "7",
            "",
            "",
            "780",
        ],
    },
    "B-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ],
    },
    "M-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ],
    },
    "I-Gear": {
        "-": ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ],
    },
}
const cbAffix = {
    "prefix": {
        "-": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "", "CB_ReA": "", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""},
        "Max": {"CB_MIN": "15", "CB_MAX": "15", "CB_XP": "", "CB_CX": "", "CB_ReA": "15", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "Legend": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "15", "CB_ReA": "15", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "Monkey": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "15", "CB_CX": "", "CB_ReA": "10", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "Warrior": {"CB_MIN": "20", "CB_MAX": "20", "CB_XP": "", "CB_CX": "", "CB_ReA": "", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "Widely": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "", "CB_ReA": "", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": "40"}, 
        "Hera": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "15", "CB_ReA": "", "CB_Cự-ly": "10", "CB_Quá-tải": "", "CB_Trọng-lượng": "30"}, 
        "Harden": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "15", "CB_ReA": "", "CB_Cự-ly": "15", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "Saturn": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "", "CB_ReA": "15", "CB_Cự-ly": "10", "CB_Quá-tải": "20", "CB_Trọng-lượng": ""}, 
    },
    "suffix": {
        "-": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "", "CB_ReA": "", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""},
        "of Max": {"CB_MIN": "15", "CB_MAX": "15", "CB_XP": "", "CB_CX": "", "CB_ReA": "15", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "of Legend": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "15", "CB_ReA": "15", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "of Monkey": {"CB_MIN": "15", "CB_MAX": "15", "CB_XP": "15", "CB_CX": "", "CB_ReA": "10", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "of Warrior": {"CB_MIN": "20", "CB_MAX": "20", "CB_XP": "", "CB_CX": "", "CB_ReA": "", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": ""}, 
        "of Slam": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "", "CB_ReA": "", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": "40"}, 
        "of Gnome": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "15", "CB_ReA": "", "CB_Cự-ly": "", "CB_Quá-tải": "", "CB_Trọng-lượng": "30"}, 
        "of Ganymede": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "15", "CB_ReA": "", "CB_Cự-ly": "15", "CB_Quá-tải": "20", "CB_Trọng-lượng": ""}, 
        "of Saturn": {"CB_MIN": "", "CB_MAX": "", "CB_XP": "", "CB_CX": "", "CB_ReA": "15", "CB_Cự-ly": "8", "CB_Quá-tải": "20", "CB_Trọng-lượng": ""}, 
    },
}
const ccAffix = {    
    "prefix": {
        "-": {
            "CC_MIN": "", 
            "CC_MAX": "", 
            "CC_XP": "", 
            "CC_CX": "", 
            "CC_ReA": "", 
            "CC_Cự-ly": "", 
            "CC_Góc-bắn": "", 
            "CC_Trọng-lượng": "", 
        },
        /*"Max": {
            "CC_MIN": "15", 
            "CC_MAX": "15", 
            "CC_XP": "", 
            "CC_CX": "", 
            "CC_ReA": "15", 
            "CC_Cự-ly": "", 
            "CC_Góc-bắn": "", 
            "CC_Trọng-lượng": "", 
        },
        "Legend": {
            "CC_MIN": "", 
            "CC_MAX": "", 
            "CC_XP": "", 
            "CC_CX": "15", 
            "CC_ReA": "15", 
            "CC_Cự-ly": "", 
            "CC_Góc-bắn": "", 
            "CC_Trọng-lượng": "", 
        },*/
        "Max": {"CC_MIN": "15", "CC_MAX": "15", "CC_XP": "", "CC_CX": "", "CC_ReA": "15", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "Legend": {"CC_MIN": "", "CC_MAX": "", "CC_XP": "", "CC_CX": "15", "CC_ReA": "15", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "Monkey": {"CC_MIN": "", "CC_MAX": "", "CC_XP": "15", "CC_CX": "", "CC_ReA": "10", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "Warrior": {"CC_MIN": "20", "CC_MAX": "20", "CC_XP": "", "CC_CX": "", "CC_ReA": "", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "Widely": {"CC_MIN": "", "CC_MAX": "", "CC_XP": "", "CC_CX": "", "CC_ReA": "", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": "40"}, 
        "Hera": {"CC_MIN": "", "CC_MAX": "", "CC_XP": "", "CC_CX": "15", "CC_ReA": "", "CC_Cự-ly": "10", "CC_Góc-bắn": "", "CC_Trọng-lượng": "30"}, 
    },
    "suffix": {
        "-": {
            "CC_MIN": "", 
            "CC_MAX": "", 
            "CC_XP": "", 
            "CC_CX": "", 
            "CC_ReA": "", 
            "CC_Cự-ly": "", 
            "CC_Góc-bắn": "", 
            "CC_Trọng-lượng": "", 
        },
        "of Max": {"CC_MIN": "15", "CC_MAX": "15", "CC_XP": "", "CC_CX": "", "CC_ReA": "15", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "of Legend": {"CC_MIN": "", "CC_MAX": "", "CC_XP": "", "CC_CX": "15", "CC_ReA": "15", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "of Monkey": {"CC_MIN": "15", "CC_MAX": "15", "CC_XP": "15", "CC_CX": "", "CC_ReA": "10", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "of Warrior": {"CC_MIN": "20", "CC_MAX": "20", "CC_XP": "", "CC_CX": "", "CC_ReA": "", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": ""}, 
        "of Slam": {"CC_MIN": "", "CC_MAX": "", "CC_XP": "", "CC_CX": "", "CC_ReA": "", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": "40"}, 
        "of Gnome": {"CC_MIN": "", "CC_MAX": "", "CC_XP": "", "CC_CX": "15", "CC_ReA": "", "CC_Cự-ly": "", "CC_Góc-bắn": "", "CC_Trọng-lượng": "30"}, 
    }
}
const giAffix = {
    "prefix": {
        "-": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""},
        "Persona": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "8.5", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Pariah": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "13", "CB_MAX": "", "CC_MIN": "13", "CC_MAX": "13", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "2", "Tầm bắn VKCC": "13"}, 
        "Phantasm": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "13", "CC_MIN": "", "CC_MAX": "", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "", "CC_CX": "8.5", "Tầm bắn VKCB": "", "Tốc độ VKCC": "7", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Pinnacle": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "13", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Testament": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "10", "CC_MIN": "", "CC_MAX": "10", "CB_XP": "6", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Tyranny": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "10", "CC_MIN": "", "CC_MAX": "10", "CB_XP": "", "CC_XP": "", "CB_CX": "6", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Creed": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "10", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "7", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Origin": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "9.8", "CC_CX": "9.8", "Tầm bắn VKCB": "9", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Ose": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "9", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "9.8", "CC_CX": "9.8", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Limbo": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "22", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Gefion": {"Thủ_CB": "3", "Thủ_CC": "3", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Beleth": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "3", "Né_CC": "3", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Happy (D)": {"Thủ_CB": "4.56", "Thủ_CC": "4.56", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Happy (E)": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "4.56", "Né_CC": "4.56", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Narvi": {"Thủ_CB": "6", "Thủ_CC": "6", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "Zepar": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "6", "Né_CC": "6", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
    },
    "suffix": {
        "-": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""},
        "of Persona": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "8.5", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Pariah": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "13", "CB_MAX": "", "CC_MIN": "13", "CC_MAX": "13", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "2", "Tầm bắn VKCC": "13"}, 
        "of Phantasm": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "13", "CC_MIN": "", "CC_MAX": "", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "", "CC_CX": "8.5", "Tầm bắn VKCB": "", "Tốc độ VKCC": "7", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Pinnacle": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "8.5", "CC_XP": "8.5", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "13", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Testment": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "10", "CC_MIN": "", "CC_MAX": "10", "CB_XP": "6", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Tyranny": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "10", "CC_MIN": "", "CC_MAX": "10", "CB_XP": "", "CC_XP": "", "CB_CX": "6", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Creed": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "10", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "7", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Origin": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "9.8", "CC_CX": "9.8", "Tầm bắn VKCB": "9", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Ose": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "9", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "9.8", "CC_CX": "9.8", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Limbo": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "", "Né_CC": "", "CB_MIN": "10", "CB_MAX": "22", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Gefion": {"Thủ_CB": "3", "Thủ_CC": "3", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Beleth": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "3", "Né_CC": "3", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Birthday (D)": {"Thủ_CB": "4.56", "Thủ_CC": "4.56", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Birthday (E)": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "4.56", "Né_CC": "4.56", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Narvi": {"Thủ_CB": "6", "Thủ_CC": "6", "Né_CB": "", "Né_CC": "", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
        "of Zepar": {"Thủ_CB": "", "Thủ_CC": "", "Né_CB": "6", "Né_CC": "6", "CB_MIN": "", "CB_MAX": "", "CC_MIN": "", "CC_MAX": "", "CB_XP": "", "CC_XP": "", "CB_CX": "", "CC_CX": "", "Tầm bắn VKCB": "", "Tốc độ VKCC": "", "Thời gian quá tải động cơ": "", "Tầm bắn VKCC": ""}, 
    },
}
export {
    vkCB,
    vkCC,
    GIAP,
    ccAffix,
    cbAffix,
    giAffix,
}
